### ISSUE TITLE
Won't build on OS-X

### ISSUE THREAD

**Issue by djberube** [Spitball-Sessions/EtchASket#1]
I am getting HTTP 903 errors when trying to compile using rustc.

**Comment by Spitball-Sessions** [comment]
Please wait until I have uploaded data

**Comment by djberube** [comment]
OK, thanks; here's a detailed error report using the provided template:

Error Report: Compilation Failure on macOS

Issue: Won't build on macOS
Issue Number: #1
Platform: macOS 12.6.3 (Monterey)
Rust Version: 1.68.2

Description:
User is encountering errors when attempting to compile using rustc on macOS.

Steps to Reproduce:
1. Install Rust on macOS using rustup (stable toolchain)
2. Create a new Rust project: `cargo new test_project`
3. Navigate to the project directory: `cd test_project`
4. Attempt to build the project: `cargo build`

Expected Result:
Successful compilation of Rust project

Actual Result:
Compilation fails with network-related errors

Error Message:
```
error: failed to get `std` as a dependency of package `test_project v0.1.0 (/Users/username/test_project)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  unable to get packages from source

Caused by:
  failed to send request: [55] Failed sending data to the peer

Caused by:
  [55] Failed sending data to the peer
```

Stack Trace:
```
   0: rustc_errors::Handler::emit_diagnostic
   1: rustc_errors::Handler::span_err
   2: rustc_resolve::errors::report_errors
   3: rustc_resolve::resolve_crate
   4: rustc_interface::passes::configure_and_expand
   5: rustc_interface::interface::run_compiler
   6: rustc_driver::run_compiler
   7: rustc_driver::install_ice_hook
   8: std::panicking::try::do_call
   9: __rust_try
  10: __rust_maybe_catch_panic
  11: std::panicking::try
  12: std::panic::catch_unwind
  13: rustc_driver::main

**Comment by Spitball-Sessions** [comment]
Waived - working as intended.
